version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR ...
      - echo check environment variable ...
      - echo "AWS_ACCOUNT_ID=\"$AWS_ACCOUNT_ID\""
      - echo "AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\""
      - echo "ENVIRONMENT_NAME=\"$ENVIRONMENT_NAME\""
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker images ...
      - python ./cicd/run.py build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images ...
      - python ./cicd/run.py push
